---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: mdegat01/addon-workflows/.github/workflows/base-deploy.yaml@main
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
